name: pheli_fla_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  
  cloud_firestore: ^4.13.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1

  flutter_localizations:
    sdk: flutter
  provider: ^6.1.0
  intl: ^0.19.0

  package_info_plus: ^4.0.2
  http: ^1.2.1
  html: ^0.15.4
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/Gaming.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/PheliFlaLogo.png
    - assets/images/PheliFlafundo.png
    - assets/images/cadastrouser.png
    - assets/images/Gaming.png
    - assets/images/fundos/PheliFlafundo.png
    - assets/images/fundos/ArrascaetaFundo.png
    - assets/images/fundos/fundoAdidas.png
    - assets/images/fundos/fundo2019.png
    - assets/images/fundos/FundoBH.png
    - assets/images/fundos/fundoerik.png
    - assets/images/fundos/Pedro.png
    - assets/images/fundos/UrubuFundo.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
