// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtxqY77Zemi4-_wbet7TAel61d9hw_iYg',
    appId: '1:803919627793:web:50d318972cccc436fd13b0',
    messagingSenderId: '803919627793',
    projectId: 'phelifla-chat',
    authDomain: 'phelifla-chat.firebaseapp.com',
    storageBucket: 'phelifla-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcJeNi0_yKTuk4TV_HNLF87M3T8QLHdY',
    appId: '1:803919627793:android:df7de56b49382c0efd13b0',
    messagingSenderId: '803919627793',
    projectId: 'phelifla-chat',
    storageBucket: 'phelifla-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZJRWziniUEn0x2kJFBKkP7nB-RL6kDow',
    appId: '1:803919627793:ios:73f187ef45f07165fd13b0',
    messagingSenderId: '803919627793',
    projectId: 'phelifla-chat',
    storageBucket: 'phelifla-chat.firebasestorage.app',
    iosBundleId: 'com.example.flamengoChat',
  );
}
